### PR TITLE
Set server-side mock data in development mode.

### PR DESCRIPTION
**Pull request by murashi-sn**
This is suggestion.
In development, `google.mock` does not return response that I assume. So I think it is useful that `google.mock` has method which setup mock data. I implemented as following.
* Users can set mockdata, and server-side function success or failed.
* In product mode, mock data file is not bundled by webpack.

How about that ?

### CODE REVIEW

**Comment by cmlima** [comment]
Sorry about the delay and thanks for contributing.

Your propposal seems a very nice idea, but since this is a new feature we are going to need some documentation. Along with the changes your are propposing, please add the appropriate explanations to the README file, so that other developers may understand how the whole mocking process works and how they can adjust it to their needs.

Also, please change "This is product mode" to "This is production mode".

**Comment by murashi-sn** [comment]
@cmlima 

Sorry for not replying you earlier.
Thank your for your feedback! I will work on this issue. I will modify code and README. And my code I commited was duty, so I will refactor my code.
But I will be late to finish this task for personal reasons... I will contact you later in this PR.

**Comment by murashi-sn** [comment]
@cmlima 
I modified implementation to use [Webpack DefinePlugin](https://webpack.js.org/plugins/define-plugin/), and changed wording.
I ask question before I will modify README. 
* File path which has mock response is now, `./src/mock-data/responseMock.js`.  is it OK?

**Comment by cmlima** [comment]
Yes, sure 

Enviado do meu iPhone

**Comment by murashi-sn** [comment]
@cmlima 
I added explanations to the README file. Would you confirm README? 
I'm not good at english... Thank you for your cooperation.

**Pull request merged**
